### ISSUE TITLE
Download Tiles: Tile selection fails

### ISSUE THREAD

**Issue by dabasler** [bluegreen-labs/daymetr#10]
Tile download does nothing when bounding box is passed as location argument:

https://github.com/khufkens/daymetr/blob/e9faa371d1c8e7da174a078cceddc20e22a7533c/R/download_daymet_tiles.r#L102

loops through tiles instead of  tile_selection
also 
https://github.com/khufkens/daymetr/blob/e9faa371d1c8e7da174a078cceddc20e22a7533c/R/download_daymet_tiles.r#L47

should set tile_selection not tiles

**Comment by khufkens** [comment]
Fixed
