### ISSUE TITLE
download_daymet fails if path = tempdir() and intern = FALSE

### ISSUE THREAD

**Issue by dschlaep** [bluegreen-labs/daymetr#12]
This is with version 1.2 installed today with commit a68b39c3964c9769f4bfd838215e377c854f6d95: 

The call `download_daymet(path = tempdir(), internal = FALSE)` fails with message
> Error in file.copy(daymet_tmp_file, daymet_file, overwrite = TRUE, copy.mode = FALSE) :
file can not be copied both 'from' and 'to'

because the arguments are such that `daymet_tmp_file` and `daymet_file` are identical.

The current code that throws the error is:
```
  file.copy(daymet_tmp_file, daymet_file, overwrite = TRUE,
    copy.mode = FALSE)
  file.remove(daymet_tmp_file)
```

A suggestion to fix this behavior is to only copy and delete tmp-file if not identical to the one from the user requested path, e.g., wrap the above lines in a if-condition:
```
  if (!identical(normalizePath(daymet_tmp_file), normalizePath(daymet_file))) {
    file.copy(daymet_tmp_file, daymet_file, overwrite = TRUE,
      copy.mode = FALSE)
    file.remove(daymet_tmp_file)
  }
```

Thank you very much for making your package available! We are using it in our research work https://github.com/Burke-Lauenroth-Lab/rSFSW2

**Comment by khufkens** [comment]
Sorry, only noticed this now. Can you explain your use case? You store everything in a temporary directory? This means that all data gets destroyed upon closing a session (requiring you to download everything again), correct?

**Comment by khufkens** [comment]
Ah got it, you are querying this within another package and don't want to expose the data to users. I would think tough that you could use the internal = TRUE option store data in a nested list for the same purpose (might be cleaner). -- fixed for now using your implementation (will raise a message however, no error or warning).
