### ISSUE TITLE
Installing the github pkg in R 3.2.2

### ISSUE THREAD

**Issue by laurareads** [bluegreen-labs/daymetr#2]
Hi, I would like to use your R code for downloading tiles from Daymet.  I receive an error that the package is not available for R version 3.2.2.   Has anyone else encountered this? I'm running on a windows machine through R Studio.

**Comment by khufkens** [comment]
I'll get back to you later. I'm writing grants which takes priority. However, try to update to the latest version of R first.

**Comment by laurareads** [comment]
fixed with new version. now i have another error, but you can get back to me when you have time. thanks.

**Comment by khufkens** [comment]
What is the error you talked about, I haven't seen a new ticket...

**Comment by khufkens** [comment]
Fixed the issue, was a URL and package issue. Should work now.
