### ISSUE TITLE
Error in download_daymet: more columns than columns names

### ISSUE THREAD

**Issue by alvaroparedesl** [bluegreen-labs/daymetr#27]
First of all, thanks fot his package, it has been very usefull.

Today I ran my routine to extract data and this error pop up. I dig a little and find out that apparently Daymet changed the download file and added some lines (or modified them). I don't know if this change is permanent, but changing the skip value in tile (line 182) to 4, alt to 5 (line 188) and data to 8 (line 195) fix the problem for the actual format.

**Comment by aaronspringford** [comment]
@ccfv I changed the lineskips and made a pull request.

**Comment by khufkens** [comment]
Thanks for catching this, this also explains why my phenocamr package doesn't build cleanly anymore (so I can rule out the change to R 3.5)! I'll merge your pull request, but will think of a more permanent (dynamic solution should ORNL change the header format again).

**Comment by khufkens** [comment]
I'll close this for now and open a new ticket for a more dynamic solution.
