### ISSUE TITLE
Spatial vs. temporal coverage

### ISSUE THREAD

**Issue by bbcrown** [bluegreen-labs/daymetr#30]
The function download_daymet returns an error like: 

> Your requested data is outside DAYMET (temporal) coverage, or the server can't be reached. Check your the connection to the server or the coordinates and start/end years!

simply when the coordinates are outside of the spatial coverage. It think the error message should be edited to become accurate, otherwise it is confusing.

**Comment by khufkens** [comment]
I'll roll it into a new version if new additions are made (more summary functions). I'll flag it non-critical for now.

**Comment by khufkens** [comment]
semantics, close for now

**Comment by ethanwhite** [comment]
I just ran into this issue and found it pretty confusing.

**Comment by khufkens** [comment]
Fixed in dev version:
https://github.com/khufkens/daymetr/commit/a97c19b46deebd0746cc9b9690ea4ffaed502c5d

**Comment by ethanwhite** [comment]
Awesome! Thanks!!
