### ISSUE TITLE
projection to EPSG:4326 does not work correctly

### ISSUE THREAD

**Issue by vishalm1975** [bluegreen-labs/daymetr#36]
Hi,

I'm sure that the projection from LCC to EPSG 4326, as in the daymetr vignette (https://cran.r-project.org/web/packages/daymetr/vignettes/daymetr-vignette.html), is not working correctly.

I've tried it many times and the projection transformation is not correct. It ends up as a very small extent, with exceptionally  high resolution output in the wrong place.

I'm referring to the section of the vignette: "Querying netCDF subset (ncss) data"

```r
# to set the correct projection use
raster::projection(r) <- "+proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-100 +x_0=0 +y_0=0 +a=6378137 +b=6356752.314706705 +units=m +no_defs"

# reproject to lat lon
r <- raster::projectRaster(r, crs = "+init=epsg:4326")
plot(R)
```

Even if you look at the ouput of plot(r), i think this is visible..it seems to be an extent of only approx 42.4929 to 42.4933 degrees latitude, which is less than 1km (0.00833) so less than 1 pixel (since daymet is 1 km resolution). The output image however shows many pixels..

I tried with CDO and NCO. I think this is a problem in how the netcdf file is being read. The units of measure in the netcdf are listed as km. Should it be m?

Also, Daymet documentation says that the LCC transform is based on wgs 84 datum an dhas only one parameter a listed (no b parameter is listed). Should that info be included?

Hope you can resolve this, as i'm counting on using this package which i think is great!!

Thank you,
Vishal

**Comment by khufkens** [comment]
Hi Vishal,

Could you provide a worked example or a solution which works for you? If so, do a pull request with the corrections in the vignette Rmd. This is the quickest way to fix this.

Cheers,
K

**Comment by vishalm1975** [comment]
Hi koen,
I managed to solve it yesterday. It's to do with how the projection
information is interpreted by r (I guess by the gdal library)

I'll post the solution sometime today.
Thanks for replying. I was just thinking of  calling you to discuss this.

Best,
Vishal

**Comment by khufkens** [comment]
Thanks Vishal! Much appreciated!

Could you mention the (r)gdal version if you are at it? I think their was a recent major update and I want to make sure that this isn't something to do with this.

Cheers,
K

**Comment by vishalm1975** [comment]
Hi all,

The correct projection string to apply to the downloaded Daymet data is as follows:
raster::projection(r) <- "+proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5  +lon_0=-100 +x_0=0 +y_0=0 +ellps=WGS84 +units=km +no_defs"

Also, i was using R 64 bit version 3.5.1  (2018-07-02) and rgdal package version 1.4-3

The main issue i believe is the definition of units (kilometers works correctly, meters does not).

Best,
Vishal

**Comment by khufkens** [comment]
Yep, seems to work. Thanks for catching this bug. Feel free to do a pull request, if not I'll correct it later myself.

**Comment by vishalm1975** [comment]
go head koen,
i'm embaressed to say i dont quite know github, so feel free to make the change.
cheers!
Vishal

**Comment by khufkens** [comment]
Ok, no problem.

Fixed with: https://github.com/khufkens/daymetr/commit/96eb2fb4557e543ad3d8d206f8033c4ca6961495

**Comment by khufkens** [comment]
Example as this popped up again.

```r
library(daymetr)
library(raster)
require(sp)
require(maps)

download_daymet_tiles(tiles = 11755, param = "prcp", start = 1980, end = 1980)
r <- raster::raster(file.path(tempdir(),"prcp_1980_11755.nc"))
raster::projection(r) <- "+proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-100 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs"
r <- raster::projectRaster(r, crs = "+init=epsg:4326")

map("usa", xlim = c(-72.5, -69), ylim = c(40.4,42.5))
plot(r, add = TRUE)
```

**Comment by khufkens** [comment]
The final answer plus demo code is now listed here

https://github.com/khufkens/daymetr/issues/40
