### ISSUE TITLE
download_daymet_ncss() not downloading some variables

### ISSUE THREAD

**Issue by johnwendt** [bluegreen-labs/daymetr#49]
The function is not working for `param = "srad"` with `frequency = "monthly"` or `frequency = "annual"`. Tested with CRAN version and GitHub version. Also, `param = "ALL"` only downloaded tmin, tmax, prcp, and vp.

`download_daymet_ncss(location = c(50, -114, 40, -97),
                     start = 1980,
                     end = 1980,
                     param = "ALL",
                     frequency = "monthly",
                     mosaic = "na",
                     path = "D:/NGP/data/daymet")`

This returns the generic "data download failed" error message.

**Comment by khufkens** [comment]
This is all which is available for the summary values. Not all variables are made available. This goes back to a previous issue, but I forgot to update the docs in the new release.

https://github.com/bluegreen-labs/daymetr/issues/44
