### ISSUE TITLE
Issues with download.daymet

### ISSUE THREAD

**Issue by jungej62** [bluegreen-labs/daymetr#5]
I am unable to download any daymet data with the download.daymet function. I receive the following error message, even when using the example code found on the help site.

> cldat<- download.daymet(site="Oak Ridge National Laboratories",lat=36.0133,lon=-84.2625,start_yr=1980,end_yr=2010,internal=TRUE)
> Downloading DAYMET data for: Oak Ridge National Laboratories at 36.0133/-84.2625 latitude/longitude !
> Error in download.daymet(site = "Oak Ridge National Laboratories", lat = 36.0133,  : 
>   You requested data is outside DAYMET coverage,
>            the file is empty --> check coordinates! 

I am running R version 3.3.1 and using the following packages as dependencies: sp 1.2-3; rgdal 1.1-10; downloader 0.4. I am using Windows 7 Enterprise.

**Comment by khufkens** [comment]
#I feel this is a windows issue with the downloader package or implementation thereof. I have no windows system which makes it really hard to debug these kind of things. I'll try moving things to the libcurl library which should work better cross platform.

A similar ticket has been filed earlier, which I dismissed as it does not occur on *nix based systems (which I have access to - as my main development machines).

**Comment by khufkens** [comment]
# #4

For additional updates I refer to the first instance of these Windows errors.
