### ISSUE TITLE
Download functions not linking correctly to FTP servers?

### ISSUE THREAD

**Issue by cyaneus87** [bluegreen-labs/daymetr#51]
download_daymet_ncss() or download_daymet_tiles() on daily tmin,tmax or prcp and others are downloading blank (NULL) files to my path folder.

https://thredds.daac.ornl.gov/thredds/ncss/ornldaac/1840/daymet_v4_daily_na_prcp_2019.nc

on the Daymet websites'  thredds server link, seems like they provide different paths on their server.

See- 
https://thredds.daac.ornl.gov/thredds/catalog/ornldaac/2129/catalog.html?dataset=2129/daymet_v4_daily_na_tmax_2009.nc

Is this a simple version mismatch issue?

Thank you in advance!

**Comment by khufkens** [comment]
Hi @cyaneus87

The github (dev) release addresses this. But other work obligations have prevented me from pushing a new release to CRAN. Install the latest github release to address this issue.

K
