### ISSUE TITLE
Identify key variables in download_daymet_batch

### ISSUE THREAD

**Issue by spencer-tassone** [bluegreen-labs/daymetr#59]
Is it possible to identify which variables a user is interested in when accessing many sites using ```download_daymet_batch```? For instance, I am only interested in ```TMAX``` and ```TMIN``` in my analysis and do not need the other variables that ```daymetr``` provides. Being able to identify which variables are of interest inside the ```download_daymet_batch()``` function could cut down on memory usage and increase processing speed.

**Comment by khufkens** [comment]
I don't think you will gain that much speed. You can try to fix this for yourself to test by altering this line:
https://github.com/bluegreen-labs/daymetr/blob/f2238b05fd561a4add8a51f988e5f3404e8628d2/R/download_daymet.r#L123

(only retaining tmax and tmin) on a clone of the project.

Install the altered version by hitting the install button in the build panel when in the project, and see if you see performance gains.

![Screenshot from 2023-05-20 18-51-58](https://github.com/bluegreen-labs/daymetr/assets/1354258/ebfc1ec3-1b13-4cd3-8414-6327d45ffa6a)

The reason I don't allow this flexibility is that the overhead is relatively low (IMO) and more time can be gained by parallelizing things or scheduling nightly downloads (batch jobs). Note, there might be a rate limiter active on the server so I would not push for more than 10 parallel downloads from the same location.

**Comment by khufkens** [comment]
Another alternative is using my `appeears` package. Not yet on CRAN but it should allow for fast scheduling and it won't block a session as the API call is asynchronously processed in the cloud (similar to my `ecmwfr` package). Still under review so you will have to use the development install from github.

https://bluegreen-labs.github.io/appeears/
