### ISSUE TITLE
Missing data for Leap days

### ISSUE THREAD

**Issue by gshelor** [bluegreen-labs/daymetr#65]
When I use daymet_download() to download data at a single pixel for a leap year, it only returns data for 365 days when it should return data for 366 days.

**Comment by khufkens** [comment]
The data is provided as is, I don't do any post-processing on the data which would remove this. Check the original data description, data often get regularized for model purposes.

**Comment by khufkens** [comment]
https://www.nature.com/articles/s41597-021-00973-0
