### ISSUE TITLE
internal = TRUE, internal = FALSE, same result

### ISSUE THREAD

**Issue by Ranae** [bluegreen-labs/daymetr#9]
I'm so happy to find such a valuable package today. Thank you!  

I am running this in Windows, which may be the source of the problem, but when I download data for both a single site, or for a batch, it is *always* saved as a .csv in the working directory.  

I can work like this, but thought you might want to know.

**Comment by khufkens** [comment]
Hi Ranae, this is an inconsistency in my naming convention. I use "assign", "data.frame" and FALSE. I'll fix this as it is confusing. For now you can change your code to "data.frame" instead of TRUE and it should provide values in your R workspace.

**Comment by khufkens** [comment]
Fixed this issue now is consistent with TRUE or FALSE behaviour.
